
import java.io.File;
import java.io.FileNotFoundException;
import java.util.ArrayList;
import java.util.Scanner;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JTable;
import javax.swing.filechooser.FileNameExtensionFilter;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author kamen
 */
public class first extends javax.swing.JFrame {
       
    private final JFileChooser file_chooser;
    private File inputTrading212CSVFile;
    private Scanner scanner;
    private ContentTableModel contentTableModel = new ContentTableModel();
	private PostgreSQLUtility pgUtil = new PostgreSQLUtility();
    
    /**
     * Creates new form first
     */
    public first() {
        initComponents();
        
        file_chooser = new JFileChooser();
        file_chooser.setFileFilter(new FileNameExtensionFilter("Trading212 Export files","csv"));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        uploadeXLSXFileButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        contentTable = new javax.swing.JTable();
        uploadMessage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        uploadeXLSXFileButton.setText("Upload xlsx file");
        uploadeXLSXFileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uploadeXLSXFileButtonActionPerformed(evt);
            }
        });

        contentTable.setModel(contentTableModel);
        jScrollPane1.setViewportView(contentTable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 476, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(uploadMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(uploadeXLSXFileButton, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(uploadeXLSXFileButton)
                        .addGap(12, 12, 12)
                        .addComponent(uploadMessage)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 468, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void uploadeXLSXFileButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uploadeXLSXFileButtonActionPerformed
        // TODO add your handling code here:
        int returnValue = file_chooser.showOpenDialog(this);
        if (returnValue == JFileChooser.APPROVE_OPTION) {
            inputTrading212CSVFile = file_chooser.getSelectedFile();
            try {
                scanner = new Scanner(inputTrading212CSVFile);
                scanner.nextLine();
            } catch (FileNotFoundException ex) {
                uploadMessage.setText("File not found.");
            }
            uploadMessage.setText("File import successful.");
            
            // start uploading the records to the CSVRecords
            ArrayList<CSVRecord> csvRecords = new ArrayList<>();
            while (scanner.hasNextLine()) {
                String line = scanner.nextLine();
                Object lineValues[] = line.split(",");
                CSVRecord csvRecord = new CSVRecord();
                csvRecord.setAction(lineValues[0].toString());
                csvRecord.setDate(lineValues[1].toString());
                csvRecord.setTicker(lineValues[3].toString());
                csvRecord.setName(lineValues[4].toString());
                csvRecord.setNumberOfShares(Double.parseDouble(lineValues[5].toString()));
                csvRecord.setPricePerShare(Double.parseDouble(lineValues[6].toString()));
                csvRecord.setCurrency(lineValues[7].toString());
                csvRecord.setExchangeRate(Double.parseDouble(lineValues[8].toString()));
                if (!lineValues[9].equals("")) {
                    csvRecord.setResult(Double.parseDouble(lineValues[9].toString()));
                } else {
                    csvRecord.setResult(null);
                }
                csvRecord.setTotalCost(Double.parseDouble(lineValues[10].toString()));
                if (lineValues.length == 13) {
                    csvRecord.setCurrencyConverstionFee(Double.parseDouble(lineValues[12].toString()));
                } else {
                    csvRecord.setCurrencyConverstionFee(null);
                }
                csvRecords.add(csvRecord);
            }
            contentTable.setModel(new ContentTableModel(csvRecords));
            contentTableModel.fireTableDataChanged();
            
            String tableName = "rawDataFromFile";
            pgUtil.insertRowsToTable(csvRecords, tableName);
			pgUtil.truncateTable(tableName);
            
            
            
        } else {
           uploadMessage.setText("No file chosen.");
        }
    }//GEN-LAST:event_uploadeXLSXFileButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(first.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(first.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(first.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(first.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JFrame jf = new first();
                jf.setExtendedState(JFrame.MAXIMIZED_BOTH);
                jf.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable contentTable;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel uploadMessage;
    private javax.swing.JButton uploadeXLSXFileButton;
    // End of variables declaration//GEN-END:variables
}
